version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Premo900
      MYSQL_DATABASE: webshoppp
    ports:
      - "3307:3307"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

  app:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - "5000:5000"
    networks:
      - mysql-network
    depends_on:
      - mysql
      - frontend 

  frontend:
    build:
      context: ./react2
      dockerfile: Dockerfile  
    container_name: frontend-container
    ports:
      - "3000:3000"
    networks:
      - mysql-network
    depends_on:
      - mysql  
volumes:
  mysql-data:
networks:
  mysql-network:
    driver: bridge